---
- name: Verificar ejecución con privilegios escalados en Windows
  hosts: all
  gather_facts: no

  tasks:
    - name: Mostrar usuario actual (debe ser el 'Run As')
      win_shell: whoami
      register: resultado

    - name: Mostrar resultado
      debug:
        msg: "Se ejecutó como: {{ resultado.stdout }}"
