- name: Reporte Simple de Uso de Disco
  hosts: lab
  gather_facts: yes
  become: no

  tasks:
    - name: Recopilar información de todos los discos
      delegate_to: localhost
      run_once: true
      ansible.builtin.set_fact:
        reporte_por_host: |
          {% set reporte = {} %}
          {% for host in ansible_play_hosts_all %}
            {% set discos_del_host = [] %}
            {% for mount in hostvars[host].get('ansible_mounts', []) %}
              {% set uso_pct = 0 %}
              {% if mount.size_total > 0 %}
                {% set uso_pct = (((mount.size_total - mount.size_available) * 100) / mount.size_total) | round | int %}
              {% endif %}
              {% set _ = discos_del_host.append({
                  'mount': mount.mount,
                  'usage': uso_pct,
                  'total_gb': (mount.size_total / (1024*1024*1024)) | round(1)
                }) %}
            {% endfor %}
            {% set _ = reporte.update({host: discos_del_host}) %}
          {% endfor %}
          {{ reporte }}

    - name: Mostrar reporte simple
      delegate_to: localhost
      run_once: true
      ansible.builtin.debug:
        msg: |
          {% for host, discos in (reporte_por_host | from_yaml).items() %}
          
          --- {{ host }} ---
          {% for disco in discos %}
          - {{ disco.mount }}: {{ disco.usage }}%
          {% endfor %}
          {% endfor %}
