# install_ssh_key.yml
- name: Copiar clave pública para ansible.adm
  hosts: lab
  become: true
  tasks:
    - name: Crear carpeta .ssh si no existe
      ansible.builtin.file:
        path: /home/ansible.adm/.ssh
        state: directory
        owner: ansible.adm
        group: unix-infraestructura 
        mode: '0700'

    - name: Copiar clave pública al archivo authorized_keys
      ansible.builtin.copy:
        src: /home/ansible.adm/.ssh/id_rsa.pub
        dest: /home/ansible.adm/.ssh/authorized_keys
        owner: ansible.adm
        group: unix-infraestructura
        mode: '0644'
        remote_src: no

