---
- name: Reporte de Estado de Servicios
  hosts: lab
  become: yes
  vars:
    servicios_a_revisar:
      - sshd.service
      - crond.service
      - firewalld.service
      - zabbix-agent.service
      - traps_pmd.service
      - sssd.service
      - vmtoolsd.service
      - oddjobd.service
  tasks:
    - name: Recolectar estado de todos los servicios
      ansible.builtin.service_facts:
    
    - name: Generar reporte desde la plantilla
      delegate_to: localhost
      run_once: true
      ansible.builtin.template:
        src: tpl_estado_servicios.md.j2
        dest: "/tmp/reporte_estado_servicios_{{ ansible_date_time.iso8601_basic_short }}.md"
      vars:
        # Pasar explícitamente la lista de hosts
        hosts_to_process: "{{ groups['lab'] }}"
      register: reporte_generado
    
    - name: Leer el contenido del reporte generado
      delegate_to: localhost
      run_once: true
      ansible.builtin.slurp:
        src: "{{ reporte_generado.dest }}"
      register: contenido_del_reporte
    
    - name: Mostrar reporte final en consola
      delegate_to: localhost
      run_once: true
      ansible.builtin.debug:
        msg: "{{ (contenido_del_reporte.content | b64decode).split('\n') }}"
    
    - name: Mostrar ubicación del archivo
      delegate_to: localhost
      run_once: true
      ansible.builtin.debug:
        msg: "Reporte generado en: {{ reporte_generado.dest }}"
