---
- name: Probar WinRM con runas (become en Windows)
  hosts: all
  gather_facts: no
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "DOMINIO\\Administrador"
    ansible_become_password: "TuPasswordSegura"

  tasks:
    - name: Ejecutar whoami como usuario elevado
      win_shell: whoami
      register: resultado

    - name: Mostrar el usuario actual (debería ser DOMINIO\Administrador)
      debug:
        msg: "Usuario actual: {{ resultado.stdout }}"
