- name: Verificar Paquetes Desactualizados en Consola
  hosts: lab
  gather_facts: yes # No necesitamos facts generales para esta tarea

  tasks:
    - name: Obtener la lista de paquetes con actualizaciones pendientes
      become: yes
      ansible.builtin.dnf:
        list: updates
      register: dnf_updates

    - name: Procesar y mostrar el reporte de actualizaciones
      delegate_to: localhost
      run_once: true
      ansible.builtin.debug:
        msg: |
          {% set hosts_con_updates = [] %}
          {% for host in ansible_play_hosts_all %}
            {% if hostvars[host].get('dnf_updates', {}).get('results', []) | length > 0 %}
              {% set _ = hosts_con_updates.append(host) %}
            {% endif %}
          {% endfor %}
          ---
          📦 Reporte de Paquetes Desactualizados ({{ ansible_date_time.date }})
          ---
          {% if hosts_con_updates | length > 0 %}
          {% for host in hosts_con_updates %}
          
          --- {{ host }} ({{ hostvars[host].dnf_updates.results | length }} paquetes) ---
            {% for pkg in hostvars[host].dnf_updates.results %}
            - {{ pkg.name }}
            {% endfor %}
          {% endfor %}
          {% else %}
          ✅ Todos los servidores están actualizados.
          {% endif %}
          ---
