---
- name: Probar conexión con Windows
  hosts: lab
  gather_facts: yes
  tasks:
    - name: Mostrar información del sistema
      win_shell: systeminfo
      register: system_info

    - name: Mostrar salida de systeminfo
      debug:
        var: system_info.stdout_lines
