- name: Reporte de Estado de Servicios
  hosts: lab
  gather_facts: yes
  become: yes

  vars:
    servicios_a_revisar:
      - sshd.service
      - crond.service
      - firewalld.service
      - zabbix-agent.service
      - traps_pmd.service
      - sssd.service
      - vmtoolsd.service
      - oddjobd.service

  tasks:
    - name: Recolectar estado de todos los servicios
      ansible.builtin.service_facts:

    - name: Imprimir encabezado del reporte para el host
      ansible.builtin.debug:
        msg: "--- Reporte de Estado para [{{ inventory_hostname }}] ---"

    - name: Mostrar estado de cada servicio
      ansible.builtin.debug:
        msg: >-
          Servicio: {{ item }}
          {% if item in ansible_facts.services %}
            {% set srv = ansible_facts.services[item] %}
            | Estado: {{ '✅ Activo' if srv.state == 'running' else '❌ Inactivo' }}
            | Habilitado al inicio: {{ '✅ Sí' if srv.status == 'enabled' else 'ℹ️ No' }}
          {% else %}
            | Estado: ❓ No Encontrado
          {% endif %}
      loop: "{{ servicios_a_revisar }}"
