---
- name: Reporte de Estado de Servicios
  hosts: lab
  become: yes
  vars:
    servicios_a_revisar:
      - sshd.service
      - crond.service
      - firewalld.service
      - zabbix-agent.service
      - traps_pmd.service
      - sssd.service
      - vmtoolsd.service
      - oddjobd.service
  tasks:
    - name: Recolectar estado de todos los servicios
      ansible.builtin.service_facts:
    
    - name: Generar reporte inline
      delegate_to: localhost
      run_once: true
      become: no
      ansible.builtin.copy:
        content: |
          # Reporte de Estado de Servicios - {{ ansible_date_time.date }}
          
          {% for host in groups['lab'] %}
          {% if hostvars[host].ansible_facts is defined and hostvars[host].ansible_facts.services is defined %}
          ## ➞ Servidor: {{ hostvars[host].inventory_hostname }}
          
          | Servicio | Estado | Habilitado al Iniciar |
          |----------|--------|-----------------------|
          {% for servicio in servicios_a_revisar %}
          {% if servicio in hostvars[host].ansible_facts.services %}
          {% set srv = hostvars[host].ansible_facts.services[servicio] %}
          | `{{ srv.name }}` | {{ '✅ Corriendo' if srv.state == 'running' else '❌ Detenido' }} | {{ '✅ Sí' if srv.status == 'enabled' else 'ℹ️ No' }} |
          {% else %}
          | `{{ servicio }}` | ❌ No Encontrado | --- |
          {% endif %}
          {% endfor %}
          
          {% endif %}
          {% endfor %}
        dest: "/tmp/reporte_estado_servicios_{{ ansible_date_time.iso8601_basic_short }}.md"
      register: reporte_generado
    
    - name: Leer el contenido del reporte generado
      delegate_to: localhost
      run_once: true
      become: no
      ansible.builtin.slurp:
        src: "{{ reporte_generado.dest }}"
      register: contenido_del_reporte
    
    - name: Mostrar reporte final en consola
      delegate_to: localhost
      run_once: true
      become: no
      ansible.builtin.debug:
        msg: "{{ (contenido_del_reporte.content | b64decode).split('\n') }}"
    
    - name: Mostrar ubicación del archivo
      delegate_to: localhost
      run_once: true
      become: no
      ansible.builtin.debug:
        msg: "Reporte generado en: {{ reporte_generado.dest }}"
