---
- name: Reporte de Sistema, Recursos y Agentes
  hosts: lab
  gather_facts: yes
  become: no

  vars:
    reporte_resultado: []

  tasks:
    - name: Verificar si el agente de Zabbix está instalado
      stat:
        path: /usr/sbin/zabbix_agentd
      register: zabbix_agent_status

    - name: Verificar si Cortex está instalado
      stat:
        path: /usr/local/bin/cortex
      register: cortex_agent_status

    - name: Armar reporte por host
      set_fact:
        reporte_host: |
          ## Host: {{ inventory_hostname }}
          - CPU: {{ ansible_processor_cores }} cores, {{ ansible_processor_count }} procesadores
          - Memoria: Total {{ ansible_memtotal_mb }} MB, Disponible {{ ansible_memfree_mb }} MB
          - Disco raíz: {{ ansible_mounts[0].size_total | int // (1024*1024) }} MB total
          - Zabbix: {{ 'Presente' if zabbix_agent_status.stat.exists else 'No instalado' }}
          - Cortex: {{ 'Presente' if cortex_agent_status.stat.exists else 'No instalado' }}
      delegate_to: localhost
      run_once: false

    - name: Agregar reporte del host a la lista global
      set_fact:
        reporte_resultado: "{{ reporte_resultado + [reporte_host] }}"
      delegate_to: localhost
      run_once: false

    - name: Mostrar reporte completo
      debug:
        msg: "{{ reporte_resultado }}"
      delegate_to: localhost
      run_once: true

    - name: Guardar reporte en archivo local (opcional)
      copy:
        content: "{{ reporte_resultado | join('\n\n') }}"
        dest: "/tmp/reporte_recursos_{{ ansible_date_time.iso8601_basic_short }}.md"
      delegate_to: localhost
      run_once: true
