---
- name: Reporte de Estado de Servicios
  hosts: lab
  gather_facts: yes
  become: yes

  vars:
    servicios_a_revisar:
      - sshd.service
      - crond.service
      - firewalld.service
      - zabbix-agent.service
      - traps_pmd.service
      - sssd.service
      - vmtoolsd.service
      - oddjobd.service

  tasks:
    - name: Recolectar estado de todos los servicios
      ansible.builtin.service_facts:

    - name: Generar reporte por host
      ansible.builtin.debug:
        msg: |
          ## ➞ Servidor: {{ inventory_hostname }}

          {% for servicio in servicios_a_revisar %}
          {% if servicio in ansible_facts.services %}
          {% set srv = ansible_facts.services[servicio] %}
          - {{ srv.name }}:
              Estado: {{ '✅ Corriendo' if srv.state == 'running' else '❌ Detenido' }}
              Habilitado al iniciar: {{ '✅ Sí' if srv.status == 'enabled' else 'ℹ️ No' }}
          {% else %}
          - {{ servicio }}: ❌ No encontrado
          {% endif %}
          {% endfor %}
