- name: Reporte de Estado de Servicios (Método SU)
  hosts: lab
  gather_facts: yes

  # --- CAMBIO PRINCIPAL ---
  # Cambiamos el método de escalada a 'su'
  become: yes
  become_method: su

  # --- SECCIÓN 'vars' CORREGIDA ---
  # Unificamos las dos secciones en una sola
  vars:
    servicios_a_revisar:
      - sshd.service
      - crond.service
      - firewalld.service
      - zabbix-agent.service
      - traps_pmd.service
      - sssd.service
      - vmtoolsd.service
      - oddjobd.service

  tasks:
    - name: Recolectar estado de todos los servicios
      ansible.builtin.service_facts:

    - name: Generar y mostrar reporte consolidado en consola
      delegate_to: localhost
      run_once: true
      ansible.builtin.shell: |
        echo -e "
        {% for host in ansible_play_hosts_all %}
        --- Reporte de Estado para [{{ host }}] ---\n
          {% for servicio in servicios_a_revisar %}
            {% set srv = hostvars[host].ansible_facts.services.get(servicio) %}
            {% if srv %}
        - {{ '%-25s' | format(servicio) }} | Estado: {{ '%-12s' | format('✅ Activo' if srv.state == 'running' else '❌ Inactivo') }} | Habilitado: {{ '✅ Sí' if srv.status == 'enabled' else 'ℹ️ No' }}\n
            {% else %}
        - {{ '%-25s' | format(servicio) }} | Estado: ❓ No Encontrado\n
            {% endif %}
          {% endfor %}
        \n
        {% endfor %}
        "
      args:
        warn: false
      changed_when: false
