---
- name: Reporte de Sistema, Recursos y Agentes
  hosts: lab
  gather_facts: yes
  become: no

  vars:
    reporte_resultado: []

  tasks:
    - name: Verificar si el agente de Zabbix está instalado
      stat:
        path: /usr/sbin/zabbix_agentd
      register: zabbix_agent_status

    - name: Verificar si Cortex está instalado
      stat:
        path: /usr/local/bin/cortex
      register: cortex_agent_status

    - name: Armar reporte por host
      set_fact:
        reporte_host: |
          ## Host: {{ inventory_hostname }}
          - CPU: {{ ansible_processor_cores }} cores, {{ ansible_processor_count }} procesadores
          - Memoria: Total {{ ansible_memtotal_mb }} MB, Disponible {{ ansible_memfree_mb }} MB
          - Disco raíz: {{ ansible_mounts[0].size_total | int // (1024*1024) }} MB total
          - Zabbix: {{ 'Presente' if zabbix_agent_status.stat.exists else 'No instalado' }}
          - Cortex: {{ 'Presente' if cortex_agent_status.stat.exists else 'No instalado' }}

    - name: Mostrar reporte del host
      debug:
        msg: "{{ reporte_host }}"
